name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  repository:
    description: Local file path to the git repository. Defaults to the current directory (`.`)
    required: false
    default: '.'
  service-name:
    required: true
    description: 'The name that appears in the slack message'
    default: ''
  slack-webhook-url:
    required: true
    description: 'Webhook URL for slack messages'
runs:
  using: 'node12'
  main: 'dist/index.js'
